//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgDb
{
    [Serializable]
    public class H264Msg : Message
    {
        public const string k_RosMessageName = "tms_msg_db/H264";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public byte[] data;

        public H264Msg()
        {
            this.header = new Std.HeaderMsg();
            this.data = new byte[0];
        }

        public H264Msg(Std.HeaderMsg header, byte[] data)
        {
            this.header = header;
            this.data = data;
        }

        public static H264Msg Deserialize(MessageDeserializer deserializer) => new H264Msg(deserializer);

        private H264Msg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "H264Msg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
