//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgDb
{
    [Serializable]
    public class ColoredMeshMsg : Message
    {
        public const string k_RosMessageName = "tms_msg_db/ColoredMesh";
        public override string RosMessageName => k_RosMessageName;

        public Shape.MeshTriangleMsg[] triangles;
        public Geometry.PointMsg[] vertices;
        public Std.ColorRGBAMsg[] vertex_colors;
        public Geometry.Vector3Msg[] vertex_normals;

        public ColoredMeshMsg()
        {
            this.triangles = new Shape.MeshTriangleMsg[0];
            this.vertices = new Geometry.PointMsg[0];
            this.vertex_colors = new Std.ColorRGBAMsg[0];
            this.vertex_normals = new Geometry.Vector3Msg[0];
        }

        public ColoredMeshMsg(Shape.MeshTriangleMsg[] triangles, Geometry.PointMsg[] vertices, Std.ColorRGBAMsg[] vertex_colors, Geometry.Vector3Msg[] vertex_normals)
        {
            this.triangles = triangles;
            this.vertices = vertices;
            this.vertex_colors = vertex_colors;
            this.vertex_normals = vertex_normals;
        }

        public static ColoredMeshMsg Deserialize(MessageDeserializer deserializer) => new ColoredMeshMsg(deserializer);

        private ColoredMeshMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.triangles, Shape.MeshTriangleMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.vertices, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.vertex_colors, Std.ColorRGBAMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.vertex_normals, Geometry.Vector3Msg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.triangles);
            serializer.Write(this.triangles);
            serializer.WriteLength(this.vertices);
            serializer.Write(this.vertices);
            serializer.WriteLength(this.vertex_colors);
            serializer.Write(this.vertex_colors);
            serializer.WriteLength(this.vertex_normals);
            serializer.Write(this.vertex_normals);
        }

        public override string ToString()
        {
            return "ColoredMeshMsg: " +
            "\ntriangles: " + System.String.Join(", ", triangles.ToList()) +
            "\nvertices: " + System.String.Join(", ", vertices.ToList()) +
            "\nvertex_colors: " + System.String.Join(", ", vertex_colors.ToList()) +
            "\nvertex_normals: " + System.String.Join(", ", vertex_normals.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
