//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgDb
{
    [Serializable]
    public class TmsdbTerrainImageSrvRequest : Message
    {
        public const string k_RosMessageName = "tms_msg_db/TmsdbTerrainImageSrv";
        public override string RosMessageName => k_RosMessageName;

        public string type;

        public TmsdbTerrainImageSrvRequest()
        {
            this.type = "";
        }

        public TmsdbTerrainImageSrvRequest(string type)
        {
            this.type = type;
        }

        public static TmsdbTerrainImageSrvRequest Deserialize(MessageDeserializer deserializer) => new TmsdbTerrainImageSrvRequest(deserializer);

        private TmsdbTerrainImageSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "TmsdbTerrainImageSrvRequest: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
