//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgDb
{
    [Serializable]
    public class TmsdbTerrainImageSrvResponse : Message
    {
        public const string k_RosMessageName = "tms_msg_db/TmsdbTerrainImageSrv";
        public override string RosMessageName => k_RosMessageName;

        public string time;
        public string type;
        public int id;
        public string filename;
        public float terrainheight;
        public float terrainwidth;
        public float terrainelevation;
        public float offset_x;
        public float offset_y;
        public Sensor.ImageMsg image;

        public TmsdbTerrainImageSrvResponse()
        {
            this.time = "";
            this.type = "";
            this.id = 0;
            this.filename = "";
            this.terrainheight = 0.0f;
            this.terrainwidth = 0.0f;
            this.terrainelevation = 0.0f;
            this.offset_x = 0.0f;
            this.offset_y = 0.0f;
            this.image = new Sensor.ImageMsg();
        }

        public TmsdbTerrainImageSrvResponse(string time, string type, int id, string filename, float terrainheight, float terrainwidth, float terrainelevation, float offset_x, float offset_y, Sensor.ImageMsg image)
        {
            this.time = time;
            this.type = type;
            this.id = id;
            this.filename = filename;
            this.terrainheight = terrainheight;
            this.terrainwidth = terrainwidth;
            this.terrainelevation = terrainelevation;
            this.offset_x = offset_x;
            this.offset_y = offset_y;
            this.image = image;
        }

        public static TmsdbTerrainImageSrvResponse Deserialize(MessageDeserializer deserializer) => new TmsdbTerrainImageSrvResponse(deserializer);

        private TmsdbTerrainImageSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time);
            deserializer.Read(out this.type);
            deserializer.Read(out this.id);
            deserializer.Read(out this.filename);
            deserializer.Read(out this.terrainheight);
            deserializer.Read(out this.terrainwidth);
            deserializer.Read(out this.terrainelevation);
            deserializer.Read(out this.offset_x);
            deserializer.Read(out this.offset_y);
            this.image = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
            serializer.Write(this.type);
            serializer.Write(this.id);
            serializer.Write(this.filename);
            serializer.Write(this.terrainheight);
            serializer.Write(this.terrainwidth);
            serializer.Write(this.terrainelevation);
            serializer.Write(this.offset_x);
            serializer.Write(this.offset_y);
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "TmsdbTerrainImageSrvResponse: " +
            "\ntime: " + time.ToString() +
            "\ntype: " + type.ToString() +
            "\nid: " + id.ToString() +
            "\nfilename: " + filename.ToString() +
            "\nterrainheight: " + terrainheight.ToString() +
            "\nterrainwidth: " + terrainwidth.ToString() +
            "\nterrainelevation: " + terrainelevation.ToString() +
            "\noffset_x: " + offset_x.ToString() +
            "\noffset_y: " + offset_y.ToString() +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
