//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgUr
{
    [Serializable]
    public class TmsdbPoseWriteMsgMsg : Message
    {
        public const string k_RosMessageName = "tms_msg_ur/TmsdbPoseWriteMsg";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        public string machine_name;
        public string machine_kinds;
        public string record_name;
        public string record_type;
        public string description;
        public string write_target;
        public Geometry.PoseStampedMsg pose;
        public Sensor.JointStateMsg joints;

        public TmsdbPoseWriteMsgMsg()
        {
            this.type = "";
            this.machine_name = "";
            this.machine_kinds = "";
            this.record_name = "";
            this.record_type = "";
            this.description = "";
            this.write_target = "";
            this.pose = new Geometry.PoseStampedMsg();
            this.joints = new Sensor.JointStateMsg();
        }

        public TmsdbPoseWriteMsgMsg(string type, string machine_name, string machine_kinds, string record_name, string record_type, string description, string write_target, Geometry.PoseStampedMsg pose, Sensor.JointStateMsg joints)
        {
            this.type = type;
            this.machine_name = machine_name;
            this.machine_kinds = machine_kinds;
            this.record_name = record_name;
            this.record_type = record_type;
            this.description = description;
            this.write_target = write_target;
            this.pose = pose;
            this.joints = joints;
        }

        public static TmsdbPoseWriteMsgMsg Deserialize(MessageDeserializer deserializer) => new TmsdbPoseWriteMsgMsg(deserializer);

        private TmsdbPoseWriteMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.machine_name);
            deserializer.Read(out this.machine_kinds);
            deserializer.Read(out this.record_name);
            deserializer.Read(out this.record_type);
            deserializer.Read(out this.description);
            deserializer.Read(out this.write_target);
            this.pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.joints = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.machine_name);
            serializer.Write(this.machine_kinds);
            serializer.Write(this.record_name);
            serializer.Write(this.record_type);
            serializer.Write(this.description);
            serializer.Write(this.write_target);
            serializer.Write(this.pose);
            serializer.Write(this.joints);
        }

        public override string ToString()
        {
            return "TmsdbPoseWriteMsgMsg: " +
            "\ntype: " + type.ToString() +
            "\nmachine_name: " + machine_name.ToString() +
            "\nmachine_kinds: " + machine_kinds.ToString() +
            "\nrecord_name: " + record_name.ToString() +
            "\nrecord_type: " + record_type.ToString() +
            "\ndescription: " + description.ToString() +
            "\nwrite_target: " + write_target.ToString() +
            "\npose: " + pose.ToString() +
            "\njoints: " + joints.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
