//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgUr
{
    [Serializable]
    public class TmsdbTerrainDBPoseWriteSrvResponse : Message
    {
        public const string k_RosMessageName = "tms_msg_ur/TmsdbTerrainDBPoseWriteSrv";
        public override string RosMessageName => k_RosMessageName;

        public string id;
        public string log_data;
        public bool written;

        public TmsdbTerrainDBPoseWriteSrvResponse()
        {
            this.id = "";
            this.log_data = "";
            this.written = false;
        }

        public TmsdbTerrainDBPoseWriteSrvResponse(string id, string log_data, bool written)
        {
            this.id = id;
            this.log_data = log_data;
            this.written = written;
        }

        public static TmsdbTerrainDBPoseWriteSrvResponse Deserialize(MessageDeserializer deserializer) => new TmsdbTerrainDBPoseWriteSrvResponse(deserializer);

        private TmsdbTerrainDBPoseWriteSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.log_data);
            deserializer.Read(out this.written);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.log_data);
            serializer.Write(this.written);
        }

        public override string ToString()
        {
            return "TmsdbTerrainDBPoseWriteSrvResponse: " +
            "\nid: " + id.ToString() +
            "\nlog_data: " + log_data.ToString() +
            "\nwritten: " + written.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
