//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TmsMsgDb
{
    [Serializable]
    public class ColoredMeshSrvResponse : Message
    {
        public const string k_RosMessageName = "tms_msg_db/ColoredMeshSrv";
        public override string RosMessageName => k_RosMessageName;

        public ColoredMeshMsg colored_mesh;

        public ColoredMeshSrvResponse()
        {
            this.colored_mesh = new ColoredMeshMsg();
        }

        public ColoredMeshSrvResponse(ColoredMeshMsg colored_mesh)
        {
            this.colored_mesh = colored_mesh;
        }

        public static ColoredMeshSrvResponse Deserialize(MessageDeserializer deserializer) => new ColoredMeshSrvResponse(deserializer);

        private ColoredMeshSrvResponse(MessageDeserializer deserializer)
        {
            this.colored_mesh = ColoredMeshMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.colored_mesh);
        }

        public override string ToString()
        {
            return "ColoredMeshSrvResponse: " +
            "\ncolored_mesh: " + colored_mesh.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
